export const stateName = [
  { stateName: "Andhra Pradesh", stateCode: "01" },
  { stateName: "Arunachal Pradesh", stateCode: "02" },
  { stateName: "Assam", stateCode: "03" },
  { stateName: "Bihar", stateCode: "04" },
  { stateName: "Chhattisgarh", stateCode: "05" },
  { stateName: "Goa", stateCode: "06" },
  { stateName: "Gujarat", stateCode: "07" },
  { stateName: "Haryana", stateCode: "08" },
  { stateName: "Himachal Pradesh", stateCode: "09" },
  { stateName: "Jharkhand", stateCode: "10" },
  { stateName: "Karnataka", stateCode: "11" },
  { stateName: "Kerala", stateCode: "12" },
  { stateName: "Madhya Pradesh", stateCode: "13" },
  { stateName: "Maharashtra", stateCode: "14" },
  { stateName: "Manipur", stateCode: "15" },
  { stateName: "Meghalaya", stateCode: "16" },
  { stateName: "Mizoram", stateCode: "17" },
  { stateName: "Nagaland", stateCode: "18" },
  { stateName: "Odisha", stateCode: "19" },
  { stateName: "Punjab", stateCode: "20" },
  { stateName: "Rajasthan", stateCode: "21" },
  { stateName: "Sikkim", stateCode: "22" },
  { stateName: "Tamil Nadu", stateCode: "23" },
  { stateName: "Telangana", stateCode: "24" },
  { stateName: "Tripura", stateCode: "25" },
  { stateName: "Uttar Pradesh", stateCode: "26" },
  { stateName: "Uttarakhand", stateCode: "27" },
  { stateName: "West Bengal", stateCode: "28" },
];
